import fs from "node:fs/promises";

const headers = [
  "Paper",
  "Year",
  "Venue",
  "Task",
  "Graph Type",
  "Method Category",
  "Core Problem",
  "Main Idea",
  "Encoder",
  "View Generation",
  "Positive Pair Definition",
  "Negative Sampling",
  "Objective",
  "Claimed Contribution",
  "Theoretical Analysis",
  "Datasets",
  "Baselines",
  "Strongest Baseline",
  "Metrics",
  "Ablation",
  "Complexity",
  "Code Available",
  "Weakness",
  "Missing Experiments",
  "Hidden Assumption",
  "Possible Gap",
  "Relevance Score",
  "Evidence",
];

const rows = [
  {
    "Paper": "Variational Graph Auto-Encoders",
    "Year": "2016",
    "Venue": "NIPS Workshop on Bayesian Deep Learning",
    "Task": "link prediction; node representation learning",
    "Graph Type": "homophily citation graph; general graph",
    "Method Category": "generative",
    "Core Problem": "在无监督条件下学习图节点潜表示，并用于缺失边预测。",
    "Main Idea": "用 GCN 编码器从邻接矩阵和节点特征得到潜变量分布，再用内积解码器重构图结构。VGAE 在 GAE 基础上加入变分推断和 KL 正则，使表示具有概率解释。",
    "Encoder": "GCN",
    "View Generation": "不构造对比视图；以观测图为输入并重构 adjacency。",
    "Positive Pair Definition": "非对比式；观测边可视为重构中的正边。",
    "Negative Sampling": "link prediction 评估中使用未观测 non-edge 作为负例；训练细节以论文为准。",
    "Objective": "VAE ELBO; adjacency reconstruction; KL divergence",
    "Claimed Contribution": "提出 GAE/VGAE 框架，并展示其在 citation network link prediction 上优于传统图嵌入方法。",
    "Theoretical Analysis": "有概率生成模型和变分下界推导；没有 GCL 视角的理论分析。",
    "Datasets": "Cora; Citeseer; PubMed",
    "Baselines": "Spectral Clustering; DeepWalk; GAE; VGAE variants",
    "Strongest Baseline": "GAE",
    "Metrics": "AUC; AP",
    "Ablation": "GAE 与 VGAE 变体比较；是否使用节点特征的影响在实验中讨论。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：内积解码器表达能力有限，实验主要集中在 citation link prediction。",
    "Missing Experiments": "推断：缺少异配图、大规模图和下游 node classification 的系统验证。",
    "Hidden Assumption": "推断：相连节点在潜空间中应有较高内积相似度。",
    "Possible Gap": "推断：可研究比 adjacency reconstruction 更语义保持的图生成式预训练目标。",
    "Relevance Score": "3",
    "Evidence": "Abstract; Model section; Experiments/Table 1; official GitHub",
  },
  {
    "Paper": "Deep Graph Infomax",
    "Year": "2019",
    "Venue": "ICLR",
    "Task": "node classification; inductive node representation learning",
    "Graph Type": "homophily citation graph; social graph; inductive graph",
    "Method Category": "contrastive",
    "Core Problem": "学习不依赖人工标签的节点表示，并利用图的全局上下文提升局部表示质量。",
    "Main Idea": "DGI 最大化节点 patch 表示与全图 summary 表示之间的互信息。通过 corrupt 图或特征产生负样本，使真实局部-全局配对与噪声配对可区分。",
    "Encoder": "GCN; GraphSAGE-style encoder for inductive setting",
    "View Generation": "corruption by feature shuffling / graph corruption",
    "Positive Pair Definition": "node-graph / patch-summary positive pair",
    "Negative Sampling": "使用 corruption 生成负样本节点表示，与真实 summary 配对。",
    "Objective": "JSD mutual information estimator; binary cross-entropy discriminator",
    "Claimed Contribution": "提出可扩展的无监督图表示学习目标，并在 transductive 和 inductive benchmarks 上取得强结果。",
    "Theoretical Analysis": "使用互信息最大化和 JSD estimator 作为理论动机；没有完整泛化理论。",
    "Datasets": "Cora; Citeseer; PubMed; Reddit; PPI",
    "Baselines": "DeepWalk; node2vec; GAE; VGAE; GraphSAGE; Planetoid; Raw features",
    "Strongest Baseline": "GraphSAGE / Planetoid depending on dataset",
    "Metrics": "classification accuracy; micro-F1",
    "Ablation": "读出函数、corruption 和模型组件在实验/附录中比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：global summary 可能过粗，corruption 负样本可能过易或与真实语义不匹配。",
    "Missing Experiments": "推断：缺少系统异配图和大规模动态图验证。",
    "Hidden Assumption": "推断：有用节点表示应与整图 summary 保持高互信息。",
    "Possible Gap": "推断：设计局部上下文自适应的 summary，避免单一全局 summary 对异质区域过度平均。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Section 3 Deep Graph Infomax; Experiments tables; official GitHub",
  },
  {
    "Paper": "Strategies for Pre-training Graph Neural Networks",
    "Year": "2020",
    "Venue": "ICLR",
    "Task": "molecular property prediction; protein function prediction; transfer learning",
    "Graph Type": "molecular graph; biological network",
    "Method Category": "hybrid",
    "Core Problem": "GNN 预训练可能出现负迁移，需要合理组合 node-level 与 graph-level 预训练任务。",
    "Main Idea": "论文比较 attribute masking、context prediction 和 graph-level supervised pretraining 等策略。结论强调同时进行节点级和图级预训练可缓解负迁移并提升迁移性能。",
    "Encoder": "GIN",
    "View Generation": "masked node/edge attributes; sampled local context subgraphs",
    "Positive Pair Definition": "node-context pair; graph-label/task pair in supervised pretraining",
    "Negative Sampling": "context prediction 中使用负 context；其他预训练任务不一定使用显式负样本。",
    "Objective": "attribute reconstruction; context prediction; supervised multi-task pretraining",
    "Claimed Contribution": "系统评估 GNN 预训练策略，并提出结合 node-level 与 graph-level 的预训练流程。",
    "Theoretical Analysis": "主要为实验性研究；未见完整理论推导。",
    "Datasets": "ZINC; MoleculeNet datasets; PPI / biological function datasets",
    "Baselines": "no pretraining; supervised pretraining; node-level-only pretraining; graph-level-only pretraining; existing GNN baselines",
    "Strongest Baseline": "supervised pretraining / no pretraining depending on task",
    "Metrics": "ROC-AUC; classification accuracy",
    "Ablation": "node-level 与 graph-level 预训练任务组合、预训练数据规模和迁移设置比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：结论强依赖分子/蛋白领域，未覆盖后续 GCL 的 view design 问题。",
    "Missing Experiments": "推断：缺少异配图、推荐图和无标签大规模图的系统验证。",
    "Hidden Assumption": "推断：预训练任务捕获的局部和全局结构能迁移到下游标签语义。",
    "Possible Gap": "推断：研究如何自动选择或组合图预训练任务以避免负迁移。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Section 3 Pre-training Strategies; Experiments tables; official GitHub",
  },
  {
    "Paper": "Contrastive Multi-View Representation Learning on Graphs",
    "Year": "2020",
    "Venue": "ICML",
    "Task": "node classification; graph classification",
    "Graph Type": "homophily citation graph; general graph benchmark",
    "Method Category": "contrastive",
    "Core Problem": "现有无监督图表示方法未充分利用图的多视图结构信息。",
    "Main Idea": "MVGRL 构造 adjacency view 和 diffusion view，并跨视图最大化节点/图表示与 summary 表示之间的互信息。节点级和图级任务共享多视图对比思想。",
    "Encoder": "GCN / diffusion graph encoder",
    "View Generation": "graph diffusion; original adjacency view",
    "Positive Pair Definition": "node-summary across views; graph-summary across views",
    "Negative Sampling": "使用 corrupted samples / shuffled features 作为负样本。",
    "Objective": "JSD mutual information estimator",
    "Claimed Contribution": "提出多视图图表示学习框架，并在节点分类和图分类任务上验证有效性。",
    "Theoretical Analysis": "以互信息最大化为动机；没有完整复杂理论证明。",
    "Datasets": "Cora; Citeseer; PubMed; PPI; MUTAG; PTC-MR; IMDB-BINARY; REDDIT-BINARY 等",
    "Baselines": "DGI; GMI; DeepWalk; node2vec; InfoGraph; graph2vec; supervised GNN baselines",
    "Strongest Baseline": "DGI for node classification; InfoGraph for graph classification",
    "Metrics": "accuracy; micro-F1",
    "Ablation": "视图组合、diffusion 矩阵和 readout 相关实验。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：diffusion 预处理在大图上可能成本较高，且 diffusion view 默认同配平滑有效。",
    "Missing Experiments": "推断：缺少异配图和超大规模图的系统效率实验。",
    "Hidden Assumption": "推断：diffusion view 与 adjacency view 保留互补且语义一致的信息。",
    "Possible Gap": "推断：面向异配或动态图的自适应多视图生成机制。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on multi-view contrast; Experiments tables; official GitHub",
  },
  {
    "Paper": "GCC: Graph Contrastive Coding for Graph Neural Network Pre-Training",
    "Year": "2020",
    "Venue": "KDD",
    "Task": "node classification; graph classification; graph similarity / transfer",
    "Graph Type": "general graph; cross-network graph",
    "Method Category": "contrastive",
    "Core Problem": "GNN 通常依赖任务和数据集训练，缺少可跨网络迁移的通用预训练表示。",
    "Main Idea": "GCC 将图中的 r-ego subgraph 当作实例，采样同一 anchor 附近的两个子图作为正对。模型通过实例判别式对比学习预训练，使编码器学习可迁移结构模式。",
    "Encoder": "GIN-style graph encoder",
    "View Generation": "random-walk / ego-network subgraph sampling",
    "Positive Pair Definition": "subgraph-subgraph positive pair from same anchor/context",
    "Negative Sampling": "batch 中其他 sampled subgraphs 作为负样本。",
    "Objective": "InfoNCE / contrastive instance discrimination",
    "Claimed Contribution": "提出跨网络 GNN 预训练框架，并展示预训练模型可迁移到多种图任务。",
    "Theoretical Analysis": "主要为经验性方法；互信息/instance discrimination 是训练动机。",
    "Datasets": "多个社交、学术和网络图用于预训练；下游包括 node classification、graph classification、similarity search benchmarks",
    "Baselines": "DeepWalk; node2vec; DGI; supervised GNN; graph kernels / graph2vec 等",
    "Strongest Baseline": "DGI / supervised GNN depending on task",
    "Metrics": "accuracy; micro-F1; graph similarity metrics",
    "Ablation": "预训练数据、子图采样半径、迁移设置和模型组件比较。",
    "Complexity": "讨论了预训练和子图采样的可扩展实践；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：同 anchor 子图作为正样本可能偏向结构同质性，跨领域语义迁移边界不清。",
    "Missing Experiments": "推断：缺少对异配图和动态图预训练迁移的充分分析。",
    "Hidden Assumption": "推断：局部结构模式在不同图数据集中具有可迁移共性。",
    "Possible Gap": "推断：设计可感知任务语义与图类型差异的跨图预训练正样本定义。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Section 3 Graph Contrastive Coding; Experiments section; official GitHub",
  },
  {
    "Paper": "Deep Graph Contrastive Representation Learning",
    "Year": "2020",
    "Venue": "ICML Workshop on Graph Representation Learning and Beyond",
    "Task": "node classification",
    "Graph Type": "homophily citation/co-purchase/co-author graph",
    "Method Category": "contrastive; augmentation-based",
    "Core Problem": "需要一种直接、可扩展的节点级图对比学习框架来学习无标签节点表示。",
    "Main Idea": "GRACE 对同一图随机施加 edge dropping 和 feature masking，得到两个相关视图。模型最大化同一节点跨视图表示的一致性，并将其他节点作为负样本。",
    "Encoder": "GCN",
    "View Generation": "edge dropping; feature masking",
    "Positive Pair Definition": "same node across two augmented views",
    "Negative Sampling": "batch/all nodes 中其他节点的跨视图表示作为负样本。",
    "Objective": "InfoNCE / NT-Xent contrastive loss",
    "Claimed Contribution": "提出节点级图对比框架，并验证结构和属性增强对无监督节点分类有效。",
    "Theoretical Analysis": "主要为方法和实验；未见完整理论分析。",
    "Datasets": "Cora; Citeseer; PubMed; DBLP; Amazon Computers; Amazon Photo; Coauthor CS; Coauthor Physics",
    "Baselines": "DeepWalk; node2vec; GAE; VGAE; DGI; GMI; MVGRL",
    "Strongest Baseline": "MVGRL / GMI depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "edge dropping 与 feature masking 强度、投影头、温度参数等消融。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：随机增强容易破坏关键边或特征，负样本也可能包含同类节点。",
    "Missing Experiments": "推断：缺少异配图、动态图和大规模图的系统鲁棒性分析。",
    "Hidden Assumption": "推断：同一节点在随机扰动视图中语义保持不变。",
    "Possible Gap": "推断：学习式判断哪些边/特征应被保留或扰动，而非固定随机增强。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on graph augmentation and contrastive objective; Experiments tables; official GitHub",
  },
  {
    "Paper": "Simple Unsupervised Graph Representation Learning",
    "Year": "2022",
    "Venue": "AAAI",
    "Task": "node classification; node clustering",
    "Graph Type": "homophily citation/co-purchase/co-author graph",
    "Method Category": "contrastive",
    "Core Problem": "现有图自监督方法可能依赖复杂增强或昂贵负采样，需要更简单有效的无监督图表示学习方法。",
    "Main Idea": "SUGRL 使用图神经网络编码节点，并设计结构信息相关的自监督判别目标。方法强调简单实现和低额外成本，同时在节点分类/聚类上比较多种 GCL baseline。",
    "Encoder": "GCN",
    "View Generation": "不依赖显式随机增强；使用结构/邻域关系形成训练信号。",
    "Positive Pair Definition": "node-context / node-neighbor relation",
    "Negative Sampling": "使用结构上不相关或批内样本作为负对；具体采样按论文方法部分。",
    "Objective": "contrastive / ranking-style unsupervised objective",
    "Claimed Contribution": "提出简单的无监督图表示框架，并在多个节点任务上达到竞争结果。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; Amazon Computers; Amazon Photo; Coauthor CS; Coauthor Physics 等",
    "Baselines": "DeepWalk; GAE; VGAE; DGI; GMI; MVGRL; GRACE 等",
    "Strongest Baseline": "GRACE / MVGRL depending on dataset",
    "Metrics": "classification accuracy; NMI; ARI",
    "Ablation": "模型组件、损失项和超参数敏感性实验。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：方法简化可能牺牲对复杂图语义的建模能力，且主要验证在常见同配图。",
    "Missing Experiments": "推断：缺少异配图、动态图和跨领域迁移实验。",
    "Hidden Assumption": "推断：结构邻近关系足以提供可靠自监督信号。",
    "Possible Gap": "推断：将简单无增强目标扩展到异配和多关系图。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section; Experiments tables; official GitHub",
  },
  {
    "Paper": "Self-Supervised Graph Representation Learning via Global Context Prediction",
    "Year": "2020",
    "Venue": "arXiv",
    "Task": "node classification; graph representation learning",
    "Graph Type": "general graph; citation/social graph",
    "Method Category": "contrastive / predictive",
    "Core Problem": "现有 GNN 自监督任务多关注局部邻域，缺少显式全局上下文监督。",
    "Main Idea": "论文通过全局上下文预测构造自监督任务，使节点表示学习到与全图结构相关的信息。训练信号来自节点与全局上下文关系，而不是人工标签。",
    "Encoder": "GCN / GNN encoder",
    "View Generation": "不以随机增强为核心；通过 global context construction 形成监督信号。",
    "Positive Pair Definition": "node-global context relation",
    "Negative Sampling": "Unknown",
    "Objective": "global context prediction / self-supervised classification objective",
    "Claimed Contribution": "提出基于全局上下文预测的图自监督表示学习任务。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed and other graph benchmarks",
    "Baselines": "DeepWalk; node2vec; GAE; VGAE; DGI and supervised GNN baselines",
    "Strongest Baseline": "DGI",
    "Metrics": "classification accuracy",
    "Ablation": "Unknown",
    "Complexity": "Unknown",
    "Code Available": "Unknown",
    "Weakness": "推断：全局上下文构造方式可能对图规模和社区结构敏感。",
    "Missing Experiments": "推断：缺少与后续 GRACE/MVGRL/GraphMAE 等更强 SSL 方法的系统比较。",
    "Hidden Assumption": "推断：全局上下文标签能反映对下游任务有用的语义分区。",
    "Possible Gap": "推断：设计能同时适配同配和异配区域的层次化上下文预测任务。",
    "Relevance Score": "3",
    "Evidence": "Abstract; Method section; Experiments section",
  },
  {
    "Paper": "InfoGraph: Unsupervised and Semi-supervised Graph-Level Representation Learning via Mutual Information Maximization",
    "Year": "2020",
    "Venue": "ICLR",
    "Task": "graph classification; graph-level representation learning",
    "Graph Type": "general graph; molecular graph; social graph",
    "Method Category": "contrastive",
    "Core Problem": "如何在无监督或半监督条件下学习图级表示，并捕获不同尺度的结构信息。",
    "Main Idea": "InfoGraph 最大化 graph representation 与节点、边、三元组等局部 patch representation 之间的互信息。半监督扩展还让无监督表示与任务相关监督表示互信息最大化。",
    "Encoder": "GIN / graph neural network encoder",
    "View Generation": "不依赖随机视图增强；使用同一图的多尺度 patch 表示。",
    "Positive Pair Definition": "patch-graph positive pair within same graph",
    "Negative Sampling": "其他图中的 patch-graph 组合作为负样本。",
    "Objective": "JSD mutual information estimator",
    "Claimed Contribution": "提出图级无监督/半监督 MI 最大化框架，并在多种图分类 benchmark 上取得强性能。",
    "Theoretical Analysis": "以互信息最大化为目标动机；没有完整泛化理论。",
    "Datasets": "MUTAG; PTC; IMDB-BINARY; IMDB-MULTI; REDDIT-BINARY; REDDIT-MULTI; NCI1 等",
    "Baselines": "graph kernels; node2vec; sub2vec; graph2vec; DGI-style baselines; supervised GNN",
    "Strongest Baseline": "graph2vec / supervised GNN depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "局部 patch 层级、无监督/半监督目标和 readout 变体比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：patch-graph MI 可能鼓励捕获图身份而非任务因果语义。",
    "Missing Experiments": "推断：缺少分布外泛化、异配图和大规模图分类验证。",
    "Hidden Assumption": "推断：同一图内部的局部 patch 与全图标签语义一致。",
    "Possible Gap": "推断：研究 graph-level GCL 中 patch 选择与任务语义一致性的自动控制。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on InfoGraph; Experiments tables; official GitHub",
  },
  {
    "Paper": "Self-supervised Graph-level Representation Learning with Local and Global Structure",
    "Year": "2021",
    "Venue": "ICML",
    "Task": "graph classification; graph-level transfer",
    "Graph Type": "general graph; molecular/social graph",
    "Method Category": "contrastive; graph-level",
    "Core Problem": "图级 SSL 需要同时捕获局部结构相似性和全局语义结构，而现有方法往往只利用局部对比。",
    "Main Idea": "GraphLoG 建模图之间的局部结构关系，并引入全局语义原型/层次结构来组织图表示。方法通过局部和全局自监督信号联合学习图级表示。",
    "Encoder": "GIN / GNN graph encoder",
    "View Generation": "local graph augmentations / graph-instance relations; global semantic prototypes",
    "Positive Pair Definition": "graph-graph / graph-prototype relation",
    "Negative Sampling": "使用其他图或原型作为负例；具体策略按论文方法。",
    "Objective": "contrastive objective with local and global structure",
    "Claimed Contribution": "提出同时利用局部和全局结构的 graph-level SSL 框架。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "MoleculeNet / TUDataset-style graph classification benchmarks",
    "Baselines": "InfoGraph; GraphCL; supervised GNN; graph kernel / graph embedding baselines",
    "Strongest Baseline": "GraphCL / InfoGraph depending on dataset",
    "Metrics": "classification accuracy; ROC-AUC",
    "Ablation": "local/global component、prototype 数量和预训练策略比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：全局原型质量可能依赖数据集聚类结构。",
    "Missing Experiments": "推断：缺少动态图、异配节点图和大规模推荐图验证。",
    "Hidden Assumption": "推断：图数据集中存在稳定可学习的全局语义簇。",
    "Possible Gap": "推断：将 graph-level 原型对比扩展到异质图或多任务预训练。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section; Experiments tables; official GitHub",
  },
  {
    "Paper": "Graph Contrastive Learning with Augmentations",
    "Year": "2020",
    "Venue": "NeurIPS",
    "Task": "graph classification; molecular property prediction",
    "Graph Type": "general graph; molecular graph; social graph",
    "Method Category": "contrastive; augmentation-based",
    "Core Problem": "图对比学习缺少系统化图增强策略，不同增强对不同数据集和任务的影响不清楚。",
    "Main Idea": "GraphCL 对每个图采样两个增强视图，并让同一原图的两个视图表示靠近、不同图表示远离。论文系统评估 node dropping、edge perturbation、attribute masking、subgraph 等增强组合。",
    "Encoder": "GIN",
    "View Generation": "node dropping; edge perturbation; attribute masking; subgraph sampling",
    "Positive Pair Definition": "two augmented graph views from same graph",
    "Negative Sampling": "batch 中其他图视图作为负样本。",
    "Objective": "InfoNCE / NT-Xent",
    "Claimed Contribution": "提出通用图对比学习框架和增强组合评估，并在图分类和分子任务上验证有效性。",
    "Theoretical Analysis": "主要为实验分析；没有完整理论推导。",
    "Datasets": "MUTAG; PTC-MR; IMDB-BINARY; REDDIT-BINARY; NCI1; MoleculeNet datasets 等",
    "Baselines": "graph kernels; graph2vec; InfoGraph; supervised GNN; pretraining baselines",
    "Strongest Baseline": "InfoGraph / supervised GIN depending on dataset",
    "Metrics": "classification accuracy; ROC-AUC",
    "Ablation": "增强类型、增强强度、增强组合和迁移设置。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：增强策略需要数据集调参，随机扰动可能破坏分子或结构语义。",
    "Missing Experiments": "推断：缺少系统异配图和大规模图效率分析。",
    "Hidden Assumption": "推断：人工增强不会改变原图的语义标签。",
    "Possible Gap": "推断：自动学习语义保持的图增强，而不是手工选择增强强度。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Section on graph augmentations; Experiments/Table 1-4; official GitHub",
  },
  {
    "Paper": "Adversarial Graph Augmentation to Improve Graph Contrastive Learning",
    "Year": "2021",
    "Venue": "NeurIPS",
    "Task": "graph classification; transfer learning",
    "Graph Type": "general graph; molecular graph",
    "Method Category": "contrastive; augmentation-based; adaptive augmentation",
    "Core Problem": "随机图增强难以保证产生对下游任务有用且足够困难的视图。",
    "Main Idea": "AD-GCL 学习一个 adversarial augmenter，倾向于删除对表示学习最具挑战的边，同时编码器要在这种困难视图下保持一致。该框架用 min-max 形式替代固定随机增强。",
    "Encoder": "GIN / GNN graph encoder",
    "View Generation": "learnable adversarial edge dropping",
    "Positive Pair Definition": "original/augmented graph view pair from same graph",
    "Negative Sampling": "batch 中其他图作为负样本。",
    "Objective": "InfoNCE-style contrastive loss with adversarial augmentation objective",
    "Claimed Contribution": "提出自动、对抗式图增强器，提升 GraphCL 风格图级对比学习。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "TU graph classification datasets; MoleculeNet transfer datasets",
    "Baselines": "GraphCL; InfoGraph; supervised GNN; random augmentation variants",
    "Strongest Baseline": "GraphCL",
    "Metrics": "classification accuracy; ROC-AUC",
    "Ablation": "augmenter、边删除比例、adversarial objective 和随机增强比较。",
    "Complexity": "增加可学习增强器训练成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：对抗增强可能删除任务关键结构，且 min-max 训练稳定性依赖超参数。",
    "Missing Experiments": "推断：缺少异配节点图、动态图和超大规模图验证。",
    "Hidden Assumption": "推断：最困难但仍语义保持的边删除视图能提升泛化。",
    "Possible Gap": "推断：约束增强器显式保留语义/因果子结构，避免只追求困难度。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on adversarial augmentation; Experiments tables; official GitHub",
  },
  {
    "Paper": "Graph Contrastive Learning with Adaptive Augmentation",
    "Year": "2021",
    "Venue": "WWW",
    "Task": "node classification",
    "Graph Type": "homophily citation/co-purchase/co-author graph",
    "Method Category": "contrastive; adaptive augmentation",
    "Core Problem": "均匀随机删边和特征遮蔽忽略节点/边/特征的重要性，可能损害语义。",
    "Main Idea": "GCA 根据节点中心性估计边重要性，并根据特征与标签/结构相关性估计特征重要性。增强时更倾向扰动不重要边和特征，从而生成语义更稳定的视图。",
    "Encoder": "GCN",
    "View Generation": "adaptive edge dropping based on centrality; adaptive feature masking",
    "Positive Pair Definition": "same node across two adaptive augmented views",
    "Negative Sampling": "其他节点跨视图表示作为负样本。",
    "Objective": "InfoNCE / NT-Xent",
    "Claimed Contribution": "提出节点级自适应图增强策略，并在多个节点分类数据集上改进 GRACE。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; DBLP; Amazon Computers; Amazon Photo; Coauthor CS; Coauthor Physics",
    "Baselines": "DeepWalk; GAE; VGAE; DGI; GMI; MVGRL; GRACE",
    "Strongest Baseline": "GRACE / MVGRL depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "中心性度量、特征重要性、增强强度和各组件消融。",
    "Complexity": "需要额外计算边/特征重要性；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：中心性和特征重要性启发式可能不适合异配图或任务语义变化。",
    "Missing Experiments": "推断：缺少异配图和动态图上的 adaptive augmentation 验证。",
    "Hidden Assumption": "推断：结构中心性越高的边越应保留，低重要特征扰动不改变语义。",
    "Possible Gap": "推断：从下游无标签信号中学习任务自适应的增强重要性，而不是依赖静态中心性。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on adaptive augmentation; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "Graph Contrastive Learning Automated",
    "Year": "2021",
    "Venue": "ICML",
    "Task": "graph classification; molecular property prediction",
    "Graph Type": "general graph; molecular graph",
    "Method Category": "contrastive; adaptive augmentation",
    "Core Problem": "GraphCL 等方法需要人工选择增强类型和强度，而最佳增强策略随数据集变化。",
    "Main Idea": "JOAO 将增强选择建模为可优化分布，通过双层优化自动调整增强组合概率。模型在对比学习过程中学习当前数据集上更合适的增强策略。",
    "Encoder": "GIN",
    "View Generation": "automated selection among node dropping, edge perturbation, attribute masking, subgraph, identity",
    "Positive Pair Definition": "two augmented graph views from same graph",
    "Negative Sampling": "batch 中其他图视图作为负样本。",
    "Objective": "InfoNCE / NT-Xent with augmentation distribution optimization",
    "Claimed Contribution": "提出自动图增强选择框架 JOAO / JOAOv2，降低手工增强搜索成本。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "TU graph classification datasets; MoleculeNet transfer datasets",
    "Baselines": "GraphCL; InfoGraph; supervised GNN; random/manual augmentation baselines",
    "Strongest Baseline": "GraphCL",
    "Metrics": "classification accuracy; ROC-AUC",
    "Ablation": "自动增强分布、JOAOv2、增强强度和手工策略比较。",
    "Complexity": "引入双层优化额外成本；论文讨论训练开销，精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：增强搜索空间仍由人工预定义，自动化不等于语义保证。",
    "Missing Experiments": "推断：缺少节点级异配图和大规模图增强搜索效率实验。",
    "Hidden Assumption": "推断：最佳增强可由预定义增强算子的概率组合表达。",
    "Possible Gap": "推断：让增强算子本身可学习并受语义约束，而不仅搜索固定算子权重。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on automated augmentation; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "From Canonical Correlation Analysis to Self-supervised Graph Neural Networks",
    "Year": "2021",
    "Venue": "NeurIPS",
    "Task": "node classification; graph classification",
    "Graph Type": "homophily graph; general graph",
    "Method Category": "negative-free; redundancy-reduction",
    "Core Problem": "负样本构造在图对比学习中昂贵且可能引入 false negative，需要无负样本的防坍塌目标。",
    "Main Idea": "CCA-SSG 从 canonical correlation analysis 出发，最大化两个增强视图的同一实例相关性，同时通过 decorrelation 降低维度冗余。它不需要显式负样本。",
    "Encoder": "GCN / GNN encoder",
    "View Generation": "edge dropping; feature masking",
    "Positive Pair Definition": "same node/graph across two views",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "CCA-style correlation maximization; redundancy reduction / decorrelation",
    "Claimed Contribution": "将 CCA 与图自监督结合，提出高效无负样本 GNN SSL 目标。",
    "Theoretical Analysis": "有，从 CCA 目标推导无负样本自监督损失并讨论坍塌避免。",
    "Datasets": "Cora; Citeseer; PubMed; Amazon; Coauthor; graph classification benchmarks",
    "Baselines": "DGI; MVGRL; GRACE; GraphCL; BGRL-style / SSL baselines",
    "Strongest Baseline": "GRACE / MVGRL depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "相关性项、去相关项、增强强度和超参数敏感性。",
    "Complexity": "相对负样本对比降低 pairwise 负样本成本；精确复杂度按论文分析。",
    "Code Available": "Yes",
    "Weakness": "推断：去相关目标可能与任务所需冗余特征冲突。",
    "Missing Experiments": "推断：缺少对异配图和动态图中去相关目标是否稳定的验证。",
    "Hidden Assumption": "推断：两个增强视图共享的主要因素就是任务有用语义。",
    "Possible Gap": "推断：研究图结构下去相关目标与 heterophily / over-smoothing 的关系。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method/theory section deriving CCA-SSG; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "Augmentation-Free Self-Supervised Learning on Graphs",
    "Year": "2022",
    "Venue": "AAAI",
    "Task": "node classification; node clustering",
    "Graph Type": "homophily citation/co-purchase/co-author graph",
    "Method Category": "negative-free; augmentation-free",
    "Core Problem": "图增强可能破坏语义且需要调参，图 SSL 需要不依赖显式增强的训练方式。",
    "Main Idea": "AFGRL 用在线/目标网络结构生成节点表示，并通过局部邻居和全局语义相似性选择正样本。它避免手工构造增强视图和显式负样本。",
    "Encoder": "GCN",
    "View Generation": "augmentation-free; positive selection from local structure and global semantics",
    "Positive Pair Definition": "node-neighbor / node-semantic positive pair",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "bootstrap / BYOL-style alignment objective",
    "Claimed Contribution": "提出不依赖图增强的自监督图表示学习框架，并在节点任务上验证有效。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; Amazon Computers; Amazon Photo; Coauthor CS; Coauthor Physics 等",
    "Baselines": "DGI; GMI; MVGRL; GRACE; GCA; CCA-SSG; BGRL",
    "Strongest Baseline": "GCA / CCA-SSG depending on dataset",
    "Metrics": "classification accuracy; clustering metrics",
    "Ablation": "local positive、global positive、predictor 和 stop-gradient 组件消融。",
    "Complexity": "避免生成增强视图；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：正样本挖掘依赖初始结构/语义相似，可能放大错误邻居。",
    "Missing Experiments": "推断：缺少强异配图和动态图上的正样本可靠性分析。",
    "Hidden Assumption": "推断：局部邻居或语义近邻大多共享对下游任务有用的标签语义。",
    "Possible Gap": "推断：在异配图上学习可靠的 augmentation-free 正样本选择。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on AFGRL; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "Self-supervised Graph Neural Networks without explicit negative sampling",
    "Year": "2021",
    "Venue": "WWW Workshop",
    "Task": "node classification",
    "Graph Type": "homophily citation graph; general graph",
    "Method Category": "negative-free",
    "Core Problem": "图自监督中显式负采样可能昂贵或产生 false negative，需要探索无显式负样本训练。",
    "Main Idea": "SelfGNN 借鉴非对比式视觉 SSL，用两个网络/视图对齐节点表示，并利用 feature augmentation 与 normalization 等机制避免坍塌。它强调无需显式负样本也能学习节点表示。",
    "Encoder": "GCN / GNN encoder",
    "View Generation": "feature augmentation; graph/feature perturbation depending on setting",
    "Positive Pair Definition": "same node across two network views",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "negative-free alignment / BYOL-SimSiam-style objective",
    "Claimed Contribution": "展示无显式负采样的 GNN 自监督学习可行性。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed and related node classification datasets",
    "Baselines": "DGI; MVGRL; supervised GCN; other SSL baselines",
    "Strongest Baseline": "DGI / MVGRL depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "augmentation、batch normalization / stop-gradient 等组件比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：workshop 版本实验规模较有限，机制解释不如后续 CCA-SSG/BGRL 系统。",
    "Missing Experiments": "推断：缺少大规模图、异配图和与后续无负样本方法的比较。",
    "Hidden Assumption": "推断：网络结构和 normalization 足以避免表示坍塌。",
    "Possible Gap": "推断：系统解释图上 negative-free SSL 的防坍塌机制。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section; Experiments section; official GitHub",
  },
  {
    "Paper": "Graph Debiased Contrastive Learning with Joint Representation Clustering",
    "Year": "2021",
    "Venue": "IJCAI",
    "Task": "node classification",
    "Graph Type": "homophily citation/co-purchase graph",
    "Method Category": "contrastive; false negative / debiased",
    "Core Problem": "随机负采样会把潜在同类节点当作负样本，导致 graph contrastive learning 偏置。",
    "Main Idea": "GDCL 联合学习节点表示和聚类分配，用聚类结果估计负样本属于同类的概率。对比损失根据这种概率进行去偏，减少 false negative 的损害。",
    "Encoder": "GCN",
    "View Generation": "edge dropping; feature masking / graph augmentation",
    "Positive Pair Definition": "same node across augmented views",
    "Negative Sampling": "使用批内/全图负样本，并基于聚类估计进行 debiasing。",
    "Objective": "debiased contrastive loss with joint representation clustering",
    "Claimed Contribution": "指出并缓解 GCL 中 false negative 问题，提出联合聚类去偏框架。",
    "Theoretical Analysis": "有去偏对比目标动机和推导；完整泛化理论 Unknown。",
    "Datasets": "Cora; Citeseer; PubMed; Amazon Computers; Amazon Photo 等",
    "Baselines": "DGI; GMI; MVGRL; GRACE; GCA and clustering baselines",
    "Strongest Baseline": "GCA / GRACE depending on dataset",
    "Metrics": "classification accuracy; clustering metrics",
    "Ablation": "聚类模块、去偏项和增强策略消融。",
    "Complexity": "增加聚类估计成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：聚类早期不稳定会影响去偏质量。",
    "Missing Experiments": "推断：缺少开放类别、异配图和类别极不平衡场景分析。",
    "Hidden Assumption": "推断：聚类结构能近似真实语义类别，从而识别 false negative。",
    "Possible Gap": "推断：无类别簇假设下的 false negative 检测和自适应负样本重权重。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on joint clustering/debiasing; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "ProGCL: Rethinking Hard Negative Mining in Graph Contrastive Learning",
    "Year": "2022",
    "Venue": "ICML",
    "Task": "node classification; graph classification",
    "Graph Type": "homophily graph; general graph",
    "Method Category": "contrastive; false negative / debiased",
    "Core Problem": "hard negative mining 可以提升对比学习，但在图中 hard negatives 更可能包含 false negatives。",
    "Main Idea": "ProGCL 估计负样本为 true negative 的概率，并渐进式地将可靠 hard negatives 纳入训练。它试图避免直接强化所有 hard negatives 导致 false negative 被错误推远。",
    "Encoder": "GCN / GIN depending on node-level or graph-level task",
    "View Generation": "standard graph augmentations such as edge dropping and feature masking",
    "Positive Pair Definition": "same node/graph across augmented views",
    "Negative Sampling": "使用 hard negative mining，并通过 true-negative probability 进行渐进式重权重。",
    "Objective": "probability-aware contrastive loss / InfoNCE variant",
    "Claimed Contribution": "重新分析图对比学习中的 hard negative mining，并提出区分 true/false negative 的 ProGCL。",
    "Theoretical Analysis": "有关于 hard negative 和 true negative 概率的目标分析。",
    "Datasets": "Cora; Citeseer; PubMed; Amazon/Coauthor; graph classification datasets",
    "Baselines": "GRACE; GCA; GraphCL; AD-GCL; debiased contrastive baselines",
    "Strongest Baseline": "GCA / AD-GCL depending on task",
    "Metrics": "classification accuracy; ROC-AUC",
    "Ablation": "概率估计、渐进策略、hard negative 权重和不同基础 GCL 框架。",
    "Complexity": "增加负样本概率估计成本；精确复杂度按论文分析。",
    "Code Available": "Yes",
    "Weakness": "推断：true-negative probability 的估计可靠性依赖当前表示质量。",
    "Missing Experiments": "推断：缺少动态图和开放世界语义变化下 false negative 的评估。",
    "Hidden Assumption": "推断：相似度和训练进度可以较好地区分 true hard negatives 与 false negatives。",
    "Possible Gap": "推断：结合结构因果或标签传播不确定性来识别 false negatives。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method/theory section on ProGCL; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "Generating Counterfactual Hard Negative Samples for Graph Contrastive Learning",
    "Year": "2023",
    "Venue": "WWW",
    "Task": "node classification",
    "Graph Type": "homophily graph; general graph",
    "Method Category": "contrastive; false negative / debiased",
    "Core Problem": "GCL 需要有效 hard negatives，但直接从真实图中挖掘 hard negatives 容易混入 false negatives。",
    "Main Idea": "CGC 通过反事实思想生成 hard negative samples，使负样本在表示上接近但语义上应与 anchor 区分。该方式试图减少依赖随机负样本和错误 hard negatives。",
    "Encoder": "GCN / GNN encoder",
    "View Generation": "graph augmentations plus counterfactual negative generation",
    "Positive Pair Definition": "same node across graph views",
    "Negative Sampling": "使用生成的 counterfactual hard negatives；真实负样本策略按论文方法。",
    "Objective": "contrastive loss with counterfactual hard negatives",
    "Claimed Contribution": "提出反事实 hard negative 生成方法以改进图对比学习。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; Amazon/Coauthor-style node datasets",
    "Baselines": "DGI; MVGRL; GRACE; GCA; ProGCL / hard negative baselines",
    "Strongest Baseline": "ProGCL / GCA depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "counterfactual generator、hard negative 数量和损失组件比较。",
    "Complexity": "增加反事实样本生成成本；精确复杂度 Unknown。",
    "Code Available": "Unknown",
    "Weakness": "推断：生成的 hard negatives 是否真实语义相异难以无标签验证。",
    "Missing Experiments": "推断：缺少对生成负样本语义正确性的人工或标签后验分析。",
    "Hidden Assumption": "推断：反事实扰动能改变语义而不只是制造表示空间噪声。",
    "Possible Gap": "推断：用可解释约束或因果结构定义图上 counterfactual negatives。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on counterfactual hard negatives; Experiments/Ablation tables",
  },
  {
    "Paper": "GraphMAE: Self-Supervised Masked Graph Autoencoders",
    "Year": "2022",
    "Venue": "KDD",
    "Task": "node classification; graph classification; transfer learning",
    "Graph Type": "general graph; molecular graph",
    "Method Category": "generative; masked graph autoencoder",
    "Core Problem": "图自监督不应只依赖对比学习和手工增强，masked autoencoding 能否成为通用图预训练范式需要验证。",
    "Main Idea": "GraphMAE 随机 mask 节点特征，用 GNN encoder 编码未遮蔽图，再用 decoder 重构被遮蔽节点属性。它使用 scaled cosine error 缓解特征重构难度和数值问题。",
    "Encoder": "GCN; GAT; GIN depending on task",
    "View Generation": "node feature masking / masked attribute reconstruction",
    "Positive Pair Definition": "非对比式；masked node 与原始属性之间的重构关系。",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "masked feature reconstruction; scaled cosine error",
    "Claimed Contribution": "提出 GraphMAE，并展示 masked autoencoding 在节点和图任务上可与 GCL 方法竞争。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; OGBN-Arxiv; PPI; ZINC / MoleculeNet; TUDataset-style graph benchmarks",
    "Baselines": "DGI; MVGRL; GRACE; GCA; BGRL; GraphCL; supervised GNN",
    "Strongest Baseline": "BGRL / GCA / GraphCL depending on task",
    "Metrics": "accuracy; micro-F1; ROC-AUC; MAE for regression where applicable",
    "Ablation": "mask ratio、decoder、loss function、encoder 类型和是否重遮蔽等。",
    "Complexity": "与单视图 GNN 训练相近；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：重构节点属性可能偏向表面特征恢复，而非结构语义建模。",
    "Missing Experiments": "推断：缺少系统异配图和图结构掩码机制的深入比较。",
    "Hidden Assumption": "推断：被 mask 节点属性可由邻域上下文预测，且该预测能力能迁移到下游任务。",
    "Possible Gap": "推断：联合属性、结构和语义级 mask 的生成式图自监督。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Section 3 GraphMAE; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "GraphMAE2: A Decoding-Enhanced Masked Self-Supervised Graph Learner",
    "Year": "2023",
    "Venue": "WWW",
    "Task": "node classification; graph classification; transfer learning",
    "Graph Type": "general graph; molecular graph; large-scale graph",
    "Method Category": "generative; masked graph autoencoder",
    "Core Problem": "GraphMAE 类方法的 decoder 和重构过程仍可能不足，特别是如何强化 masked token 的语义预测。",
    "Main Idea": "GraphMAE2 引入 decoding-enhanced 设计，包括 re-mask decoding 和 latent representation prediction。它试图让解码器更充分利用上下文，并在更大图上验证 masked graph SSL。",
    "Encoder": "GCN; GAT; GIN / GNN encoder",
    "View Generation": "node feature masking; re-masking during decoding",
    "Positive Pair Definition": "非对比式；masked node/latent target reconstruction relation",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "masked feature reconstruction; latent prediction; scaled cosine error variant",
    "Claimed Contribution": "提出增强解码的 masked graph learner，并在节点/图任务及大规模图上提升 GraphMAE。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; OGBN-Arxiv; OGBN-Papers100M; graph classification / molecular datasets",
    "Baselines": "GraphMAE; BGRL; CCA-SSG; GRACE; GCA; GraphCL; supervised GNN",
    "Strongest Baseline": "GraphMAE / BGRL depending on task",
    "Metrics": "accuracy; ROC-AUC; micro-F1",
    "Ablation": "re-mask decoding、latent prediction、mask ratio、decoder depth 等。",
    "Complexity": "报告大规模图实验；具体训练复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：更复杂 decoder 可能带来额外训练成本和超参数敏感性。",
    "Missing Experiments": "推断：缺少异配图和结构扰动鲁棒性的系统实验。",
    "Hidden Assumption": "推断：增强解码阶段的重掩码能逼迫模型学习更抽象语义而非简单复制特征。",
    "Possible Gap": "推断：设计面向不同图类型自适应的 mask 与 decoding 策略。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on decoding enhancement; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "What's Behind the Mask: Understanding Masked Graph Modeling for Graph Autoencoders",
    "Year": "2023",
    "Venue": "KDD",
    "Task": "link prediction; node classification; graph representation learning",
    "Graph Type": "general graph; citation/co-purchase graph",
    "Method Category": "generative; masked graph autoencoder",
    "Core Problem": "masked graph modeling 为什么有效、mask 哪些图元素更重要仍缺少系统理解。",
    "Main Idea": "MaskGAE 研究边/结构遮蔽与图自编码器的关系，并提出 masked graph modeling 框架。它从重构被 mask 的边或结构信息出发分析 GAE 的泛化与表示能力。",
    "Encoder": "GCN / GNN encoder",
    "View Generation": "edge masking; structure masking",
    "Positive Pair Definition": "非对比式；masked edge / structure reconstruction target",
    "Negative Sampling": "link reconstruction 中使用 non-edge negatives；不是 GCL-style 负样本。",
    "Objective": "masked edge reconstruction; graph autoencoding objective",
    "Claimed Contribution": "从 masked graph modeling 角度解释和改进 GAE，提出 MaskGAE。",
    "Theoretical Analysis": "有，讨论 masked graph modeling 与图自编码/对比学习关系；具体结论以论文 theory section 为准。",
    "Datasets": "Cora; Citeseer; PubMed; OGB datasets and link prediction benchmarks",
    "Baselines": "GAE; VGAE; DGI; GRACE; GraphMAE; link prediction baselines",
    "Strongest Baseline": "GraphMAE / GAE variants depending on task",
    "Metrics": "AUC; AP; classification accuracy",
    "Ablation": "mask ratio、mask 类型、decoder 和模型组件消融。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：结构重构可能鼓励恢复观测边分布，而非学习任务相关语义。",
    "Missing Experiments": "推断：缺少动态图和异配图中结构 mask 是否有效的系统验证。",
    "Hidden Assumption": "推断：被 mask 的边或结构可由剩余图上下文可靠预测。",
    "Possible Gap": "推断：面向异配和噪声图的语义结构 mask，而非随机结构 mask。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method/theory sections on masked graph modeling; Experiments/Ablation tables; official GitHub",
  },
  {
    "Paper": "Beyond Homophily in Graph Neural Networks: Current Limitations and Effective Designs",
    "Year": "2020",
    "Venue": "NeurIPS",
    "Task": "node classification",
    "Graph Type": "heterophily graph; homophily graph",
    "Method Category": "heterophily graph learning",
    "Core Problem": "传统 GNN 的邻居聚合假设在 heterophily 图上失效，需要识别限制并设计更适合的架构。",
    "Main Idea": "H2GCN 分析 ego/neighbor separation、高阶邻域和中间表示组合对异配图的重要性。模型将自节点表示与不同阶邻域表示分开处理，以避免错误平滑。",
    "Encoder": "H2GCN",
    "View Generation": "不构造 SSL 视图；监督/半监督异配 GNN 架构设计。",
    "Positive Pair Definition": "非对比式；Unknown",
    "Negative Sampling": "不使用 GCL 负样本。",
    "Objective": "supervised cross-entropy for node classification",
    "Claimed Contribution": "系统指出 homophily 假设局限，并提出 H2GCN 设计原则和 benchmark 评估。",
    "Theoretical Analysis": "有，分析异配条件下 ego/neighbor separation 和高阶邻域的作用。",
    "Datasets": "Cora; Citeseer; PubMed; Chameleon; Squirrel; Cornell; Texas; Wisconsin; Actor 等",
    "Baselines": "GCN; GAT; GraphSAGE; MixHop; Geom-GCN; MLP",
    "Strongest Baseline": "Geom-GCN / MixHop depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "H2GCN 设计组件、高阶邻域和表示组合消融。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：不是自监督/GCL 方法，主要作为异配评价和架构背景。",
    "Missing Experiments": "推断：缺少与 GCL/GraphMAE 方法的自监督预训练比较。",
    "Hidden Assumption": "推断：显式分离 ego 与邻域表示可以缓解异配噪声。",
    "Possible Gap": "推断：将异配结构原则融入 GCL 的正负样本和增强设计。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method/theory sections; Experiments tables; official GitHub",
  },
  {
    "Paper": "Geom-GCN: Geometric Graph Convolutional Networks",
    "Year": "2020",
    "Venue": "ICLR",
    "Task": "node classification",
    "Graph Type": "heterophily graph; disassortative graph",
    "Method Category": "heterophily graph learning",
    "Core Problem": "传统基于局部邻接聚合的 GCN 难以处理结构角色相近但不直接相邻的节点关系。",
    "Main Idea": "Geom-GCN 先将图节点嵌入连续潜在空间，再根据几何邻域和结构角色关系进行聚合。它为异配图提供了不同于直接邻居聚合的空间视角。",
    "Encoder": "Geom-GCN",
    "View Generation": "不构造 SSL 视图；使用 graph embedding space 定义几何邻域。",
    "Positive Pair Definition": "非对比式；Unknown",
    "Negative Sampling": "不使用 GCL 负样本。",
    "Objective": "supervised cross-entropy for node classification",
    "Claimed Contribution": "提出几何聚合框架，并在 heterophilous benchmarks 上展示优于传统 GCN。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Chameleon; Squirrel; Cornell; Texas; Wisconsin; Actor; citation datasets",
    "Baselines": "GCN; GAT; GraphSAGE; MixHop; GCN-Cheby; MLP",
    "Strongest Baseline": "MixHop / GAT depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "几何邻域、结构邻域和模型变体比较。",
    "Complexity": "需要预计算或使用结构 embedding；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：性能可能依赖初始 graph embedding 质量和固定 split 设置。",
    "Missing Experiments": "推断：缺少自监督预训练和与现代 heterophily GNN 的全面比较。",
    "Hidden Assumption": "推断：潜在几何空间能把结构/标签相关节点放近。",
    "Possible Gap": "推断：用自监督目标学习异配图的几何视图，而非固定预嵌入。",
    "Relevance Score": "3",
    "Evidence": "Abstract; Method section; Experiments tables; official GitHub",
  },
  {
    "Paper": "Large Scale Learning on Non-Homophilous Graphs: New Benchmarks and Strong Simple Methods",
    "Year": "2021",
    "Venue": "NeurIPS",
    "Task": "node classification",
    "Graph Type": "large-scale heterophily graph",
    "Method Category": "heterophily graph learning; scalable graph learning",
    "Core Problem": "异配图研究缺少大规模 benchmark，且许多复杂 GNN 在非同配图上并不一定优于简单方法。",
    "Main Idea": "论文提出大规模 non-homophilous graph benchmarks，并提出 LINKX 等简单强方法，显式结合邻接和特征信息。它指出 minibatching 和局部聚合在异配大图上有挑战。",
    "Encoder": "LINKX; MLP-style adjacency and feature encoders",
    "View Generation": "不构造 SSL 视图。",
    "Positive Pair Definition": "非对比式；Unknown",
    "Negative Sampling": "不使用 GCL 负样本。",
    "Objective": "supervised cross-entropy for node classification",
    "Claimed Contribution": "提供大规模异配 benchmark，并展示简单模型在 non-homophilous graphs 上具有强竞争力。",
    "Theoretical Analysis": "主要为 benchmark 和方法分析；形式化理论 Unknown。",
    "Datasets": "Penn94; pokec; arXiv-year; snap-patents; genius; twitch-gamers 等",
    "Baselines": "GCN; GAT; GraphSAGE; MixHop; H2GCN; GPR-GNN; MLP",
    "Strongest Baseline": "H2GCN / MLP / LINKX variants depending on dataset",
    "Metrics": "classification accuracy; ROC-AUC for some datasets",
    "Ablation": "LINKX 组件、邻接/特征分支、数据规模和 minibatching 分析。",
    "Complexity": "讨论大规模训练和 minibatching 限制；LINKX 以简单 MLP 提升可扩展性。",
    "Code Available": "Yes",
    "Weakness": "推断：不是 SSL/GCL 方法，主要提供评价场景和强监督 baseline。",
    "Missing Experiments": "推断：缺少 GraphMAE/GCL 在这些大规模异配 benchmark 上的系统评测。",
    "Hidden Assumption": "推断：在异配图上原始邻接模式和节点特征可由简单模型直接利用。",
    "Possible Gap": "推断：构建适合大规模异配图的自监督增强和采样策略。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Benchmark/method sections; Experiments tables; official GitHub",
  },
  {
    "Paper": "Beyond Smoothing: Unsupervised Graph Representation Learning with Edge Heterophily Discriminating",
    "Year": "2023",
    "Venue": "AAAI",
    "Task": "node classification; unsupervised node representation learning",
    "Graph Type": "heterophily graph",
    "Method Category": "heterophily graph SSL; contrastive",
    "Core Problem": "无监督图表示学习常依赖平滑同配假设，在 heterophily 图中容易把不同类邻居错误拉近。",
    "Main Idea": "GREET 判别边的同配/异配性质，并用不同通道处理同配聚合与异配信息。它通过边异配判别和对比学习提升异配图表示。",
    "Encoder": "GNN encoder with homophily/heterophily channels",
    "View Generation": "edge heterophily discrimination; homophily/heterophily structural views",
    "Positive Pair Definition": "node-node / view-view relation guided by edge type",
    "Negative Sampling": "使用对比学习负样本；具体采样按方法部分。",
    "Objective": "contrastive objective plus edge heterophily discrimination objective",
    "Claimed Contribution": "提出面向异配图的无监督表示学习框架，显式区分同配边和异配边。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Chameleon; Squirrel; Actor; Cornell; Texas; Wisconsin; citation/co-purchase datasets",
    "Baselines": "DGI; MVGRL; GRACE; GCA; BGRL; H2GCN; Geom-GCN and SSL baselines",
    "Strongest Baseline": "BGRL / GCA / heterophily baselines depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "edge discriminator、双通道结构、对比损失和异配组件消融。",
    "Complexity": "增加边判别模块成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：边类型判别错误会直接影响后续表示学习。",
    "Missing Experiments": "推断：缺少动态图异配和大规模异配图上的效率分析。",
    "Hidden Assumption": "推断：边可可靠划分为同配/异配类型，并且这种划分稳定服务下游任务。",
    "Possible Gap": "推断：联合学习不确定边类型与自适应增强，避免硬划分带来的错误传播。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on edge heterophily discriminating; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Large-Scale Representation Learning on Graphs via Bootstrapping",
    "Year": "2022",
    "Venue": "ICLR",
    "Task": "node classification",
    "Graph Type": "large-scale homophily/general graph",
    "Method Category": "negative-free; scalable GCL",
    "Core Problem": "负样本对比学习在大图上需要大量 pairwise comparisons，训练和内存成本高。",
    "Main Idea": "BGRL 使用 online encoder 和 target encoder 的 bootstrapping 机制，对齐同一节点在两个增强视图中的表示。它不需要负样本，因此更适合大规模节点表示学习。",
    "Encoder": "GCN; GraphSAGE / GNN encoder",
    "View Generation": "edge dropping; feature masking",
    "Positive Pair Definition": "same node across two augmented views",
    "Negative Sampling": "不使用显式负样本。",
    "Objective": "bootstrap / BYOL-style representation alignment",
    "Claimed Contribution": "提出适合大规模图的 bootstrapped graph representation learning，避免负样本复杂度。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; Citeseer; PubMed; Amazon; Coauthor; OGBN-Arxiv; large graph benchmarks",
    "Baselines": "DGI; MVGRL; GRACE; GCA; CCA-SSG; supervised GNN",
    "Strongest Baseline": "GCA / CCA-SSG depending on dataset",
    "Metrics": "classification accuracy",
    "Ablation": "target network、predictor、EMA 参数、增强类型和大规模训练设置。",
    "Complexity": "强调无需负样本和 pairwise comparison，降低大规模训练成本。",
    "Code Available": "Yes",
    "Weakness": "推断：仍依赖随机增强语义保持，且 bootstrapping 稳定性依赖 EMA/predictor 设计。",
    "Missing Experiments": "推断：缺少异配大图和动态图上防坍塌机制验证。",
    "Hidden Assumption": "推断：同一节点两种随机增强视图保持相同语义。",
    "Possible Gap": "推断：为异配/动态图设计 scalable negative-free 图 SSL。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on bootstrapping; Experiments/scalability section; official GitHub",
  },
  {
    "Paper": "Inductive Representation Learning on Large Graphs",
    "Year": "2017",
    "Venue": "NeurIPS",
    "Task": "node classification; inductive representation learning",
    "Graph Type": "large-scale graph; social/citation/biological graph",
    "Method Category": "scalable graph representation learning",
    "Core Problem": "传统 embedding 方法不能自然泛化到未见节点，大规模图也需要采样式训练。",
    "Main Idea": "GraphSAGE 通过采样邻居并聚合邻居特征学习归纳式节点表示。无监督版本用随机游走定义正上下文，并通过负采样训练节点相似性。",
    "Encoder": "GraphSAGE",
    "View Generation": "random-walk context sampling; neighborhood sampling",
    "Positive Pair Definition": "node-context pair from random walks",
    "Negative Sampling": "从负采样分布采样不共现节点。",
    "Objective": "unsupervised skip-gram / negative sampling loss; supervised cross-entropy",
    "Claimed Contribution": "提出可归纳、可采样的大规模 GNN 框架 GraphSAGE。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Reddit; PPI; citation data",
    "Baselines": "DeepWalk; node2vec; Planetoid; supervised GCN; feature-only baselines",
    "Strongest Baseline": "GCN / node2vec depending on setting",
    "Metrics": "micro-F1; classification accuracy",
    "Ablation": "聚合器类型、邻居采样数量和监督/无监督设置比较。",
    "Complexity": "分析采样聚合使每批训练成本受采样邻居数控制。",
    "Code Available": "Yes",
    "Weakness": "推断：不是 GCL 方法，但其采样与负采样是 scalable GCL 的基础。",
    "Missing Experiments": "推断：缺少现代 GCL/GraphMAE 目标下的采样策略比较。",
    "Hidden Assumption": "推断：采样邻域包含足够代表性的局部结构和标签信息。",
    "Possible Gap": "推断：把 GraphSAGE 邻居采样与对比/掩码目标联合优化。",
    "Relevance Score": "3",
    "Evidence": "Abstract; Method section on sampling/aggregators; Experiments tables; official GitHub",
  },
  {
    "Paper": "GraphGPT: Graph Instruction Tuning for Large Language Models",
    "Year": "2024",
    "Venue": "SIGIR",
    "Task": "graph instruction following; graph question answering; node/graph reasoning",
    "Graph Type": "general graph; text-attributed graph",
    "Method Category": "graph foundation model; graph-text pretraining",
    "Core Problem": "如何让 LLM 理解图结构并完成图相关指令任务。",
    "Main Idea": "GraphGPT 将图编码器得到的结构表示对齐到 LLM 语义空间，并构造图指令数据进行 instruction tuning。它把图结构建模和语言模型能力结合起来。",
    "Encoder": "Graph neural encoder plus LLM backbone",
    "View Generation": "graph-text alignment / instruction data construction; not standard graph augmentation",
    "Positive Pair Definition": "graph-text / graph-instruction alignment pair",
    "Negative Sampling": "Unknown",
    "Objective": "graph-text alignment; instruction tuning language modeling loss",
    "Claimed Contribution": "提出面向图的 LLM instruction tuning 框架，使 LLM 具备图理解能力。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "graph instruction datasets; citation and molecule/text-attributed graph tasks as reported",
    "Baselines": "LLM baselines; graph neural models; graph-language models",
    "Strongest Baseline": "Unknown",
    "Metrics": "accuracy; task-specific QA / classification metrics",
    "Ablation": "graph encoder、alignment module、instruction data和训练阶段消融。",
    "Complexity": "涉及 LLM fine-tuning 成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：图任务表现可能强依赖指令数据质量和 LLM 先验。",
    "Missing Experiments": "推断：缺少与经典 GCL 在纯结构迁移上的直接机制比较。",
    "Hidden Assumption": "推断：图编码器表示可被有效投射到 LLM token/semantic space。",
    "Possible Gap": "推断：研究 GCL 预训练如何改善 graph-to-LLM alignment 的结构可解释性。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on graph instruction tuning; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Multi-modal Molecule Structure-text Model for Text-based Retrieval and Editing",
    "Year": "2023",
    "Venue": "Nature Machine Intelligence",
    "Task": "molecule-text retrieval; molecule editing; molecular property prediction",
    "Graph Type": "molecular graph; graph-text multimodal",
    "Method Category": "graph foundation model; graph-text contrastive pretraining",
    "Core Problem": "分子结构和自然语言描述之间缺少统一表示，限制文本驱动的分子检索和编辑。",
    "Main Idea": "MoleculeSTM 对齐分子结构编码器和文本编码器，让匹配的 molecule-text pairs 在共同空间中接近。预训练表示支持文本检索分子和文本指导的分子编辑。",
    "Encoder": "molecular GNN / molecule encoder; text Transformer encoder",
    "View Generation": "molecule-text paired views",
    "Positive Pair Definition": "matched molecule-text pair",
    "Negative Sampling": "batch 中不匹配 molecule-text pairs 作为负样本。",
    "Objective": "contrastive molecule-text alignment",
    "Claimed Contribution": "提出分子结构-文本多模态模型，支持文本检索和编辑。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "PubChem / molecule-text corpus; MoleculeNet-style downstream datasets",
    "Baselines": "molecular GNN baselines; text/molecule retrieval baselines; molecular editing baselines",
    "Strongest Baseline": "Unknown",
    "Metrics": "retrieval accuracy / ranking metrics; molecular property metrics",
    "Ablation": "结构编码器、文本编码器、对比预训练和编辑模块比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：语义对齐质量依赖文本描述质量和分子-文本配对覆盖。",
    "Missing Experiments": "推断：缺少普通非分子图上的 graph-text 对齐泛化验证。",
    "Hidden Assumption": "推断：文本描述能提供足够细粒度的分子结构/功能语义。",
    "Possible Gap": "推断：将 graph-text contrastive pretraining 扩展到 citation、recommendation 或 heterophily graphs。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on molecule-text contrastive learning; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "GraphCLIP: Enhancing Transferability in Graph Foundation Models for Text-Attributed Graphs",
    "Year": "2024",
    "Venue": "arXiv",
    "Task": "node classification; transfer learning on text-attributed graphs",
    "Graph Type": "text-attributed graph; citation/product graph",
    "Method Category": "graph foundation model; graph-text contrastive pretraining",
    "Core Problem": "Text-attributed graphs 中图结构和文本语义如何对齐以提升跨数据集迁移仍未充分解决。",
    "Main Idea": "GraphCLIP 借鉴 CLIP 思想，对齐图表示与文本表示，增强图基础模型在 text-attributed graphs 上的可迁移性。方法关注结构-文本联合表示而非单一图增强。",
    "Encoder": "GNN / graph encoder; language/text encoder",
    "View Generation": "graph-text paired views",
    "Positive Pair Definition": "matched node/graph-text pair",
    "Negative Sampling": "batch 中不匹配 graph-text pairs 作为负样本。",
    "Objective": "CLIP-style contrastive alignment",
    "Claimed Contribution": "提出面向 text-attributed graphs 的 graph-text contrastive foundation model。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "text-attributed graph benchmarks as reported in paper",
    "Baselines": "GNN baselines; language model baselines; graph foundation model baselines",
    "Strongest Baseline": "Unknown",
    "Metrics": "classification accuracy; transfer metrics",
    "Ablation": "graph/text encoder、alignment loss 和迁移设置消融。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：arXiv 工作，benchmark 覆盖和长期复现性仍需观察。",
    "Missing Experiments": "推断：缺少非文本属性图和异配图上是否仍有效的验证。",
    "Hidden Assumption": "推断：文本语义与图结构标签语义高度一致。",
    "Possible Gap": "推断：研究文本和结构冲突时的 graph-text contrastive learning。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on GraphCLIP; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Self-supervised Graph Learning for Recommendation",
    "Year": "2021",
    "Venue": "SIGIR",
    "Task": "recommendation",
    "Graph Type": "recommendation bipartite graph; user-item graph",
    "Method Category": "contrastive; augmentation-based",
    "Core Problem": "推荐中的 user-item 交互稀疏且有噪声，协同过滤 GNN 需要更鲁棒的自监督信号。",
    "Main Idea": "SGL 在 LightGCN 等推荐模型上构造多个增强视图，并最大化同一用户/物品在不同视图中的一致性。增强包括 node dropout、edge dropout 和 random walk。",
    "Encoder": "LightGCN",
    "View Generation": "node dropout; edge dropout; random walk",
    "Positive Pair Definition": "same user/item across two augmented interaction graph views",
    "Negative Sampling": "recommendation ranking 中使用负 items；contrastive loss 中 batch 内其他 user/item 为负例。",
    "Objective": "BPR loss plus InfoNCE contrastive loss",
    "Claimed Contribution": "将图自监督对比学习引入推荐，提高稀疏交互场景下的鲁棒性和准确性。",
    "Theoretical Analysis": "有关于自监督信号和监督推荐信号互补性的分析；完整理论 Unknown。",
    "Datasets": "Yelp; Amazon; Alibaba / recommendation datasets as reported",
    "Baselines": "BPR; NGCF; LightGCN; Mult-VAE; graph recommendation baselines",
    "Strongest Baseline": "LightGCN",
    "Metrics": "Recall; NDCG",
    "Ablation": "增强类型、增强强度、SSL 权重和稀疏性分组。",
    "Complexity": "增加双视图训练成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：随机 dropout 是否语义保持依赖推荐图稀疏程度。",
    "Missing Experiments": "推断：缺少对曝光偏差、时间动态和冷启动文本信息的综合分析。",
    "Hidden Assumption": "推断：删除部分用户-物品交互不会改变用户偏好语义。",
    "Possible Gap": "推断：面向推荐偏差和时间演化的自适应图增强。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on SGL augmentations; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Are Graph Augmentations Necessary? Simple Graph Contrastive Learning for Recommendation",
    "Year": "2022",
    "Venue": "SIGIR",
    "Task": "recommendation",
    "Graph Type": "recommendation bipartite graph; user-item graph",
    "Method Category": "contrastive; augmentation-free / noise-based",
    "Core Problem": "推荐图中的结构增强可能不是性能提升的必要原因，甚至可能破坏协同信号。",
    "Main Idea": "SimGCL 不对图结构做复杂增强，而是在 embedding 表示上加入均匀噪声形成对比视图。论文强调对比学习带来的表示均匀性和推荐鲁棒性。",
    "Encoder": "LightGCN",
    "View Generation": "embedding perturbation / uniform noise; no structural graph augmentation",
    "Positive Pair Definition": "same user/item under different embedding perturbations",
    "Negative Sampling": "recommendation BPR 负采样；InfoNCE 中其他 user/item 作为负例。",
    "Objective": "BPR loss plus InfoNCE contrastive loss",
    "Claimed Contribution": "质疑图结构增强必要性，提出简单噪声扰动的推荐图对比学习。",
    "Theoretical Analysis": "有关于 InfoNCE、alignment/uniformity 或表示分布的分析；具体以论文 theory section 为准。",
    "Datasets": "Yelp; Amazon-Book; Gowalla and recommendation datasets as reported",
    "Baselines": "BPR; NGCF; LightGCN; SGL; other recommendation GCL baselines",
    "Strongest Baseline": "SGL / LightGCN",
    "Metrics": "Recall; NDCG",
    "Ablation": "噪声强度、对比权重、不同增强方式和稀疏性实验。",
    "Complexity": "相比结构增强更轻量；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：embedding noise 缺少明确图语义解释，可能难以迁移到非推荐图。",
    "Missing Experiments": "推断：缺少动态图推荐和多行为推荐场景下的验证。",
    "Hidden Assumption": "推断：小幅 embedding 扰动保持用户/物品语义并提供有效正视图。",
    "Possible Gap": "推断：解释推荐 GCL 增益来自结构信息、噪声正则还是流行度去偏。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on SimGCL; Experiments/Ablation tables",
  },
  {
    "Paper": "Improving Graph Collaborative Filtering with Neighborhood-enriched Contrastive Learning",
    "Year": "2022",
    "Venue": "WWW",
    "Task": "recommendation",
    "Graph Type": "recommendation bipartite graph; user-item graph",
    "Method Category": "contrastive; neighborhood-enriched",
    "Core Problem": "推荐图对比学习中仅用同一节点跨视图作为正样本，可能忽略结构邻居和语义邻居提供的协同信号。",
    "Main Idea": "NCL 同时利用 structure neighbors 和 semantic neighbors 构造 enriched positive signals。它结合 LightGCN 推荐目标和邻域增强对比目标提升 collaborative filtering。",
    "Encoder": "LightGCN",
    "View Generation": "structure-neighbor and semantic-neighbor views / prototypes",
    "Positive Pair Definition": "user/item with structural neighbors and semantic neighbors",
    "Negative Sampling": "BPR 负采样；contrastive objective 中其他 user/item 作为负例。",
    "Objective": "BPR loss plus neighborhood-enriched contrastive loss",
    "Claimed Contribution": "提出将结构邻居和语义邻居纳入推荐图对比学习的 NCL。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Gowalla; Yelp; Amazon-Book",
    "Baselines": "BPR; NGCF; LightGCN; SGL; SimGCL and recommendation baselines",
    "Strongest Baseline": "SGL / SimGCL depending on dataset",
    "Metrics": "Recall; NDCG",
    "Ablation": "结构邻居、语义邻居、prototype 数量、对比权重和稀疏性分析。",
    "Complexity": "增加邻居发现或聚类成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：语义邻居选择质量依赖当前 embedding，早期训练可能不稳定。",
    "Missing Experiments": "推断：缺少在线/时间演化推荐和长尾 item 的详细机制分析。",
    "Hidden Assumption": "推断：结构邻居和 embedding 近邻能提供真实偏好相似性。",
    "Possible Gap": "推断：自适应区分有益邻居和 popularity-driven spurious neighbors。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on NCL; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "LightGCL: Simple Yet Effective Graph Contrastive Learning for Recommendation",
    "Year": "2023",
    "Venue": "ICLR",
    "Task": "recommendation",
    "Graph Type": "recommendation bipartite graph; user-item graph",
    "Method Category": "contrastive; scalable recommendation GCL",
    "Core Problem": "推荐 GCL 需要在保持效果的同时降低增强和训练成本，并更好捕获全局协同模式。",
    "Main Idea": "LightGCL 使用 user-item interaction matrix 的 SVD 构造全局视图，并与图卷积局部视图进行对比。它将低秩全局结构纳入推荐图对比学习。",
    "Encoder": "LightGCN / graph convolution with SVD-based view",
    "View Generation": "SVD global view; local graph convolution view",
    "Positive Pair Definition": "same user/item between local graph view and SVD global view",
    "Negative Sampling": "BPR 负采样；contrastive objective 中其他 user/item 为负例。",
    "Objective": "BPR loss plus contrastive loss",
    "Claimed Contribution": "提出简单有效的 SVD-based GCL 推荐框架，兼顾性能和效率。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Gowalla; Yelp; Amazon-Book and recommendation datasets as reported",
    "Baselines": "BPR; NGCF; LightGCN; SGL; SimGCL; NCL",
    "Strongest Baseline": "NCL / SimGCL depending on dataset",
    "Metrics": "Recall; NDCG",
    "Ablation": "SVD rank、对比权重、local/global component 和复杂度比较。",
    "Complexity": "论文强调轻量化和 SVD 视图效率；具体复杂度以方法/实验分析为准。",
    "Code Available": "Yes",
    "Weakness": "推断：SVD 低秩视图可能强化主流协同模式和 popularity bias。",
    "Missing Experiments": "推断：缺少动态图推荐和冷启动场景中 SVD 视图更新成本分析。",
    "Hidden Assumption": "推断：低秩全局协同结构保留了推荐任务的核心语义。",
    "Possible Gap": "推断：设计能抑制 popularity bias 的全局视图构造方式。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on LightGCL/SVD view; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Self-Supervised Graph Transformer on Large-Scale Molecular Data",
    "Year": "2020",
    "Venue": "NeurIPS",
    "Task": "molecular property prediction",
    "Graph Type": "molecular graph",
    "Method Category": "generative; molecular graph pretraining",
    "Core Problem": "分子属性预测缺少大规模自监督预训练框架来利用海量无标签分子。",
    "Main Idea": "GROVER 使用 GTransformer 架构，并在大规模分子数据上设计 atom/bond/context 等自监督任务。预训练后的模型迁移到多个分子性质预测任务。",
    "Encoder": "Graph Transformer / GTransformer",
    "View Generation": "masked/context molecular prediction tasks; no standard contrastive augmentation",
    "Positive Pair Definition": "非对比式为主；Unknown for contrastive pairs",
    "Negative Sampling": "Unknown",
    "Objective": "self-supervised atom/bond/context prediction; supervised fine-tuning",
    "Claimed Contribution": "提出大规模分子图 Transformer 预训练框架 GROVER。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "large-scale molecular pretraining corpus; MoleculeNet datasets",
    "Baselines": "GCN; GIN; MPNN; D-MPNN; pretraining baselines",
    "Strongest Baseline": "D-MPNN / supervised molecular GNN depending on dataset",
    "Metrics": "ROC-AUC; RMSE / MAE depending on molecular task",
    "Ablation": "预训练任务、模型规模、数据规模和组件消融。",
    "Complexity": "讨论大规模预训练设置；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：分子领域专用任务较强，迁移到普通图 GCL 的通用性有限。",
    "Missing Experiments": "推断：缺少与 GraphCL/GraphMAE 等后续方法的同协议比较。",
    "Hidden Assumption": "推断：局部化学上下文预测能学习可迁移分子语义。",
    "Possible Gap": "推断：结合分子结构-文本或 3D 几何的统一自监督预训练。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on GROVER tasks; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Pre-training Molecular Graph Representation with 3D Geometry",
    "Year": "2022",
    "Venue": "ICLR",
    "Task": "molecular property prediction; transfer learning",
    "Graph Type": "molecular graph; 3D molecular geometry",
    "Method Category": "contrastive; molecular multi-view",
    "Core Problem": "2D 分子图预训练忽略 3D 几何信息，而 3D 信息对许多分子性质重要。",
    "Main Idea": "GraphMVP 将 2D 拓扑图和 3D 几何构象作为两个视图，通过 contrastive 和 generative objectives 对齐二者。预训练模型在分子性质预测任务上迁移。",
    "Encoder": "2D GNN encoder; 3D geometry encoder",
    "View Generation": "2D molecular graph view; 3D geometry/conformer view",
    "Positive Pair Definition": "same molecule's 2D representation and 3D representation",
    "Negative Sampling": "batch 中其他 molecule 的 2D/3D 表示作为负样本。",
    "Objective": "contrastive 2D-3D alignment; generative 3D-related prediction",
    "Claimed Contribution": "提出融合 2D 拓扑与 3D 几何的分子预训练框架。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "GEOM; MoleculeNet datasets; quantum chemistry/property benchmarks",
    "Baselines": "GraphCL; GROVER; AttrMasking; ContextPred; supervised GNN/3D GNN baselines",
    "Strongest Baseline": "GROVER / GraphCL depending on dataset",
    "Metrics": "ROC-AUC; RMSE; MAE",
    "Ablation": "contrastive vs generative objectives、2D/3D encoder、预训练数据和几何视图比较。",
    "Complexity": "使用 3D conformer 带来额外计算/数据成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：依赖可用且质量较好的 3D 构象，普通图任务难以直接使用。",
    "Missing Experiments": "推断：缺少 3D 构象噪声和多构象不确定性对对比目标的系统分析。",
    "Hidden Assumption": "推断：同一分子的 2D 与 3D 视图语义一致且互补。",
    "Possible Gap": "推断：在非分子图中寻找可类比 3D 几何的外部语义视图。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on 2D-3D pretraining; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Mole-BERT: Rethinking Pre-training Graph Neural Networks for Molecules",
    "Year": "2023",
    "Venue": "ICLR",
    "Task": "molecular property prediction",
    "Graph Type": "molecular graph",
    "Method Category": "generative; contrastive; molecular pretraining",
    "Core Problem": "分子 GNN 预训练需要更合适的 tokenization 和语义保持任务，简单 mask atom 可能不足。",
    "Main Idea": "Mole-BERT 对原子环境进行离散 tokenization，并结合 masked atom prediction 和 graph-level contrastive learning。它重新设计分子预训练目标以提升迁移性能。",
    "Encoder": "GIN / molecular GNN encoder",
    "View Generation": "masked atom/token prediction; graph-level augmented views",
    "Positive Pair Definition": "same molecule across graph-level views; masked atom-token target",
    "Negative Sampling": "graph-level contrastive learning 使用 batch negatives；mask prediction 不使用 GCL 负样本。",
    "Objective": "masked atom/token prediction; graph-level contrastive loss",
    "Claimed Contribution": "提出 Mole-BERT 分子图预训练框架，强调分子 tokenization 和多任务预训练。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "ZINC / large molecular corpus; MoleculeNet datasets",
    "Baselines": "AttrMasking; ContextPred; GraphCL; JOAO; GROVER; GraphMVP",
    "Strongest Baseline": "GraphMVP / GROVER depending on dataset",
    "Metrics": "ROC-AUC; RMSE",
    "Ablation": "tokenizer、mask 目标、graph contrastive loss 和预训练数据比较。",
    "Complexity": "tokenizer 和预训练增加额外成本；精确复杂度 Unknown。",
    "Code Available": "Yes",
    "Weakness": "推断：分子 tokenization 设计领域特化，迁移到一般图不直接。",
    "Missing Experiments": "推断：缺少跨分布 scaffold split 下 token 语义稳定性的深入分析。",
    "Hidden Assumption": "推断：离散 atom/environment token 能表示可迁移化学语义。",
    "Possible Gap": "推断：为通用图学习可解释、可迁移的结构 tokenization。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on Mole-BERT; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Self-supervised Representation Learning on Dynamic Graphs",
    "Year": "2021",
    "Venue": "CIKM",
    "Task": "dynamic prediction; temporal link prediction; node classification",
    "Graph Type": "temporal / dynamic graph",
    "Method Category": "contrastive; dynamic graph SSL; debiased",
    "Core Problem": "动态图表示学习需要捕获时间演化，同时普通负采样会受动态图时间偏差影响。",
    "Main Idea": "DDGCL 针对动态图构造时间相关的自监督对比任务，并考虑 debiased sampling。模型学习随时间变化的节点/图表示以支持动态下游预测。",
    "Encoder": "dynamic GNN / temporal graph encoder",
    "View Generation": "temporal context / temporal graph views",
    "Positive Pair Definition": "same node or related temporal context across time/views",
    "Negative Sampling": "使用 debiased negative sampling for dynamic graphs；具体按论文方法。",
    "Objective": "dynamic graph contrastive loss",
    "Claimed Contribution": "提出面向动态图的自监督表示学习框架，关注时间演化和采样偏差。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "dynamic graph datasets reported in CIKM paper",
    "Baselines": "dynamic graph embedding / temporal GNN baselines; static SSL baselines",
    "Strongest Baseline": "Unknown",
    "Metrics": "AUC; AP; accuracy depending on task",
    "Ablation": "temporal view、debiased sampling 和模型组件比较。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：动态图视图和负样本定义可能强依赖时间窗口选择。",
    "Missing Experiments": "推断：缺少与后续 CLDG/DySubC 和大规模 temporal graph 方法的统一比较。",
    "Hidden Assumption": "推断：时间邻近或演化上下文能定义可靠正样本。",
    "Possible Gap": "推断：时间因果约束下的动态图对比正负样本构造。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on dynamic graph SSL/debiased sampling; Experiments/Ablation",
  },
  {
    "Paper": "Self-Supervised Dynamic Graph Representation Learning via Temporal Subgraph Contrast",
    "Year": "2023",
    "Venue": "ACM TKDD",
    "Task": "dynamic prediction; temporal link prediction; node classification",
    "Graph Type": "temporal / dynamic graph",
    "Method Category": "contrastive; dynamic graph SSL",
    "Core Problem": "动态图 SSL 需要同时捕获局部结构和时间演化模式。",
    "Main Idea": "DySubC 使用 temporal subgraph contrast 构造动态图自监督信号，将时间子图作为上下文进行对比学习。方法关注节点/子图在时间上的结构演化一致性。",
    "Encoder": "dynamic GNN / temporal graph encoder",
    "View Generation": "temporal subgraph sampling",
    "Positive Pair Definition": "temporal subgraph-subgraph / node-temporal context pair",
    "Negative Sampling": "使用其他 temporal subgraphs 或节点上下文作为负样本；具体按论文方法。",
    "Objective": "temporal subgraph contrastive loss",
    "Claimed Contribution": "提出 temporal subgraph contrast 框架用于动态图自监督表示学习。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "dynamic graph datasets reported in paper",
    "Baselines": "DeepWalk/node2vec variants; dynamic graph embedding baselines; temporal GNN baselines",
    "Strongest Baseline": "Unknown",
    "Metrics": "AUC; AP; accuracy depending on task",
    "Ablation": "subgraph sampling、时间窗口、对比损失组件和模型参数比较。",
    "Complexity": "temporal subgraph sampling 带来额外成本；精确复杂度 Unknown。",
    "Code Available": "Unknown",
    "Weakness": "推断：子图采样策略会显著影响正负样本质量。",
    "Missing Experiments": "推断：缺少跨数据集统一 temporal split 和大规模效率评测。",
    "Hidden Assumption": "推断：相近时间子图包含稳定可学习的演化语义。",
    "Possible Gap": "推断：学习式选择 temporal subgraphs，以减少时间窗口超参数依赖。",
    "Relevance Score": "4",
    "Evidence": "Abstract; Method section on temporal subgraph contrast; Experiments/Ablation",
  },
  {
    "Paper": "CLDG: Contrastive Learning on Dynamic Graphs",
    "Year": "2023",
    "Venue": "ICDE",
    "Task": "dynamic prediction; temporal link prediction",
    "Graph Type": "temporal / dynamic graph",
    "Method Category": "contrastive; dynamic graph SSL",
    "Core Problem": "静态图对比学习不能直接处理动态边和时间演化，需要动态图特有的视图与一致性目标。",
    "Main Idea": "CLDG 构造 timespan view，并利用 temporal translation invariance 约束动态表示。模型通过对比不同时间跨度的动态图视图学习稳定演化模式。",
    "Encoder": "dynamic GNN / temporal graph encoder",
    "View Generation": "timespan view generation; temporal graph views",
    "Positive Pair Definition": "same node/edge context under related timespan views",
    "Negative Sampling": "使用其他节点/时间上下文作为负样本；具体按论文方法。",
    "Objective": "contrastive loss with temporal translation invariance",
    "Claimed Contribution": "提出动态图对比学习框架 CLDG，专门建模时间跨度视图。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "dynamic graph datasets reported in ICDE paper",
    "Baselines": "dynamic graph embedding baselines; temporal GNN baselines; static contrastive baselines",
    "Strongest Baseline": "Unknown",
    "Metrics": "AUC; AP; accuracy depending on dynamic task",
    "Ablation": "timespan view、temporal translation invariance、对比损失和时间窗口设置。",
    "Complexity": "Unknown",
    "Code Available": "Yes",
    "Weakness": "推断：temporal invariance 假设可能不适合突变或周期性变化强的动态图。",
    "Missing Experiments": "推断：缺少异配动态图和大规模在线更新场景验证。",
    "Hidden Assumption": "推断：相关时间跨度下的图语义应保持可对齐。",
    "Possible Gap": "推断：面向非平稳动态图的自适应时间视图对比学习。",
    "Relevance Score": "5",
    "Evidence": "Abstract; Method section on timespan view/temporal invariance; Experiments/Ablation; official GitHub",
  },
  {
    "Paper": "Graph Contrastive Learning under Heterophily via Graph Filters",
    "Year": "2024",
    "Venue": "UAI",
    "Task": "node classification; node representation learning",
    "Graph Type": "heterophily graph; homophily graph; large-scale non-homophilous graph",
    "Method Category": "contrastive; heterophily-aware; graph-filter-based; augmentation-based",
    "Core Problem": "现有 GCL 多默认相邻节点语义相近或增强视图语义保持，在 heterophily graph 上随机增强和低通平滑容易混淆异类邻居，导致表示学习效果下降。",
    "Main Idea": "HLCL 先用特征相似性把原图划分为 homophilic subgraph 和 heterophilic subgraph，再分别用 low-pass / high-pass graph filters 构造适合同配和异配信号的增强视图。模型在两个子图上分别执行节点级对比学习，使同配区域保留平滑信息、异配区域保留差异信息。",
    "Encoder": "GCN-style encoder with low-pass and high-pass graph filters; projection head",
    "View Generation": "基于节点特征相似度划分 homophilic / heterophilic subgraphs；homophilic subgraph 使用 edge removing + feature masking 并经 low-pass filter；heterophilic subgraph 使用 node dropping + feature masking 并经 high-pass filter；论文也比较 edge adding、PPR diffusion 等增强。",
    "Positive Pair Definition": "同一节点在两个 homophilic low-pass views 中构成正对；同一节点在两个 heterophilic high-pass views 中构成正对。",
    "Negative Sampling": "显式使用跨视图其他节点作为负样本；对每个 anchor node，将另一视图中的其他节点作为 negatives，属于 in-batch / all-node negative contrast。",
    "Objective": "symmetric InfoNCE-style node-level contrastive loss with cosine similarity and temperature；总损失为 homophilic low-pass contrastive loss 与 heterophilic high-pass contrastive loss 的组合。",
    "Claimed Contribution": "提出 HLCL，将 graph filters 引入 heterophily-aware GCL；通过 homophilic / heterophilic subgraph 分离和 low-pass / high-pass 视图对比同时处理同配和异配图；给出谱域不变性相关理论分析并在多类同配/异配数据集验证。",
    "Theoretical Analysis": "有。论文从 spectral domain 分析 low-pass / high-pass filters 下的增强视图不变性，并证明特定增强下 filtered views 可保持稳定的谱信号。",
    "Datasets": "Cora; Citeseer; PubMed; Actor; Chameleon; Squirrel; Penn94; Twitch-gamers; Genius",
    "Baselines": "GCN; DGI; BGRL; GRACE; SP-GCL; HGRL; MixHop; H2GCN; CPGNN; GloGNN",
    "Strongest Baseline": "HGRL / SP-GCL among SSL baselines; GloGNN among supervised heterophily baselines",
    "Metrics": "node classification accuracy; linear evaluation accuracy",
    "Ablation": "比较不同 low-pass / high-pass filters、不同 graph augmentations、是否单独使用 homophilic 或 heterophilic representations、subgraph update interval、homophily ratio threshold，以及将 high-pass filter 加到 DGI/BGRL/GRACE 的效果。",
    "Complexity": "论文讨论 high-pass message passing 只比普通 GNN 多一次消息传递；还给出 simplified HLCL 加速版本，精确复杂度公式以论文为准。",
    "Code Available": "Yes",
    "Weakness": "论文限制指出方法依赖特征相似度近似标签相似度；当特征相似性与标签相似性不一致时，如 Penn94，子图划分可能不可靠。方法也主要验证静态节点分类，缺少 graph-text、推荐图和动态图场景。",
    "Missing Experiments": "推断：缺少 positive pair reliability 校准实验、跨 batch/mini-batch 大规模训练细节、异构图/文本属性图中的结构-语义冲突实验，以及与最新 heterophily-aware GCL 的统一比较。",
    "Hidden Assumption": "推断：节点特征相似度能够可靠区分 homophilic edges 和 heterophilic edges；同一节点经过 low-pass/high-pass filtered augmentation 后仍是可靠正样本。",
    "Possible Gap": "推断：HLCL 已覆盖 graph-filter heterophily-aware augmentation，但仍未充分解决子图划分不确定性、正样本可靠性校准和跨模态结构-文本冲突。",
    "Relevance Score": "5",
    "Evidence": "PMLR Abstract; arXiv Section 4.1 on high-pass/low-pass graph filters; Section 4.2/Theorem 1; Section 5.1 datasets/baselines; Tables 1/2/5/6; Section 6 limitations; official GitHub",
  },
  {
    "Paper": "Enhancing Homophily in Heterogeneous Graph Contrastive Learning via Connection Strength and Multi-view Self-Expression",
    "Year": "2025",
    "Venue": "SIGIR",
    "Task": "node classification; node clustering; heterogeneous node representation learning",
    "Graph Type": "heterogeneous graph; heterophily/homophily mixed graph",
    "Method Category": "contrastive; heterogeneous graph SSL; adaptive augmentation; false negative mitigation",
    "Core Problem": "Heterogeneous graph contrastive learning 依赖 metapath views，但真实异构图中不同 metapath 的同配性差异很大；低同配 metapath 会削弱 high-quality positive samples，同时相似节点也可能被错误当作负样本。",
    "Main Idea": "HGMS 用 metapath connection strength 衡量节点之间的同配关系，并据此执行 heterogeneous edge dropping，生成更同配的增强视图。随后通过 multi-view self-expression 挖掘跨视图的潜在同配关系，构造 self-expressive view 并在对比损失中缓解 false negatives。",
    "Encoder": "metapath-specific GCN encoder with semantic-level attention",
    "View Generation": "connection-strength-guided heterogeneous edge dropping；节点丢弃用于构造另一增强视图；multi-view self-expression 进一步生成 self-expressive view。",
    "Positive Pair Definition": "同一节点跨增强视图构成 instance-level positive；具有高 metapath connection strength 的 metapath-based neighbors 也被视为 positive samples。",
    "Negative Sampling": "使用对比学习中的显式 negatives；通过 multi-view self-expression 识别潜在同配/相似节点，降低 false negatives 在负样本中的影响。",
    "Objective": "contrastive loss with positive/negative sets informed by connection strength and self-expression；multi-view self-expression loss / regularization；论文还给出 mutual information lower bound 视角。",
    "Claimed Contribution": "提出 HGMS，首次系统关注 HeteroGCL 中 metapath homophily ratio 对对比学习的影响；提出 MCS-guided heterogeneous edge dropping 和 multi-view self-expression 来增强同配性并缓解 false negatives。",
    "Theoretical Analysis": "有。论文给出 heterogeneous contrastive objective 与 mutual information lower bound 的关系，并从 MCS/MHR 角度分析 high-quality positives。",
    "Datasets": "ACM; DBLP; Aminer; Freebase; IMDB; Academic",
    "Baselines": "RGCN; HAN; HGT; HGMAE; RMR; DMGI; HDMI; HeCo; HeCo++; HERO; GTC",
    "Strongest Baseline": "HeCo++; HERO; HGMAE; RMR; GTC depending on dataset/task",
    "Metrics": "Macro-F1; Micro-F1; AUC; NMI; ARI",
    "Ablation": "去掉 connection strength、去掉 heterogeneous edge dropping、去掉 multi-view self-expression、不同视图组件和超参数比较；并分析 MHR 与性能关系。",
    "Complexity": "论文给出 time complexity 分析，主要额外成本来自 metapath connection strength 计算和 multi-view self-expression；具体量级以论文复杂度小节为准。",
    "Code Available": "Yes",
    "Weakness": "推断：方法强依赖 metapath 设计和 MCS 对同配性的刻画，可能不适合缺少清晰 metapath 或同配关系动态变化的异构图；MSE 也可能引入额外计算和早期表示偏差。",
    "Missing Experiments": "推断：缺少与 HLCL/GREET 等 heterophily-specific graph SSL 的统一比较，缺少 text-attributed heterogeneous graph、动态图和超大规模异构图上的效率验证，也缺少 positive reliability 与 false positive view 的显式评测。",
    "Hidden Assumption": "推断：高 connection strength 能够近似语义同配；self-expression 发现的跨视图关系足够可靠，可以作为降低 false negative 的依据。",
    "Possible Gap": "推断：HGMS 已处理 heterogeneous graph 中的同配增强和部分 false negative mitigation，但仍未形成跨同构/异构/图文场景统一的 positive-negative reliability calibration。",
    "Relevance Score": "5",
    "Evidence": "arXiv Abstract; Section 3.3 on metapath connection strength; Section 3.4 on heterogeneous edge dropping and multi-view self-expression; Section 3.5 contrastive objective; Section 4.1 datasets/baselines; Tables 2/3/4/5; official GitHub",
  },
  {
    "Paper": "GAugLLM: Improving Graph Contrastive Learning for Text-Attributed Graphs with Large Language Models",
    "Year": "2024",
    "Venue": "KDD",
    "Task": "node classification; text-attributed graph representation learning",
    "Graph Type": "text-attributed graph; graph-text; homophily citation/product graph",
    "Method Category": "contrastive; graph-text augmentation; LLM-based augmentation; augmentation-based",
    "Core Problem": "Text-attributed graphs 同时包含结构和文本语义，传统 GCL 的随机 feature/edge augmentation 容易忽略文本语义或破坏图结构；LLM 可提供语义增强，但如何同时改进 node features 和 graph topology 仍是问题。",
    "Main Idea": "GAugLLM 使用 LLM 生成更具语义信息的增强节点文本/特征，并通过基于增强特征相似度的 edge modifier 调整图结构。它将 LLM feature augmentation 与 LLM-informed edge augmentation 接入 GCL，使 TAG 表示同时利用文本语义和结构信息。",
    "Encoder": "GNN encoder used in graph contrastive learning; LLM-assisted text encoder/feature generator",
    "View Generation": "LLM-based feature augmentation；基于 LLM 增强特征相似度的 edge modifier / edge augmentation；与 graph contrastive training 结合。",
    "Positive Pair Definition": "同一节点在原始/增强文本特征与结构视图之间构成 positive pair；具体正对按 GCL 框架中的 same-node cross-view alignment。",
    "Negative Sampling": "使用 GCL 中的 in-batch / other-node negatives；论文重点不在专门的 false negative correction。",
    "Objective": "contrastive objective for TAG representations；结合 LLM feature augmentation 和 edge-augmented views；具体 loss 以论文 Section 4 为准。",
    "Claimed Contribution": "提出首个利用 LLM 同时进行 node feature augmentation 和 graph structure augmentation 的 TAG GCL 框架；设计 edge modifier 来缓解原始结构缺陷，并在多个 TAG 数据集上提升性能。",
    "Theoretical Analysis": "Unknown",
    "Datasets": "Cora; PubMed; ogbn-arxiv; WikiCS; Instagram; Reddit",
    "Baselines": "GCN; GAT; GraphSAGE; DGI; MVGRL; GRACE; GCA; BGRL; CCA-SSG; GraphCLIP; TAPE; SimTeG",
    "Strongest Baseline": "TAPE / SimTeG / GraphCLIP depending on dataset; CCA-SSG or BGRL among graph-only SSL",
    "Metrics": "node classification accuracy",
    "Ablation": "比较是否使用 LLM feature augmentation、是否使用 edge modifier、不同 GCL backbones 与不同 LLM / augmentation settings；论文报告 ablation study。",
    "Complexity": "Unknown；LLM 生成和边修改会带来额外预处理成本，论文实验主要报告性能。",
    "Code Available": "Yes",
    "Weakness": "推断：方法已用 LLM 改进 TAG augmentation，但没有显式建模结构-文本冲突类型；LLM 生成文本可能带来幻觉或领域偏差，edge modifier 若只依赖文本相似度可能强化错误同配。",
    "Missing Experiments": "推断：缺少显式 structure-text conflict benchmark，缺少文本相似但结构相反、结构相似但文本冲突的压力测试，缺少 graph-text positive/negative reliability 校准和低质量 LLM 输出鲁棒性分析。",
    "Hidden Assumption": "推断：LLM 增强后的文本特征更接近节点真实语义，并且文本相似性可作为修正图结构的可靠依据。",
    "Possible Gap": "推断：GAugLLM 已覆盖 LLM-based TAG augmentation，但仍未系统解决 structure-text conflict、cross-modal false positive/false negative pair 和可解释的 graph-text reliability。",
    "Relevance Score": "5",
    "Evidence": "arXiv Abstract; Section 4.1 on LLM-based feature augmentation; Section 4.2 on edge modifier; Section 5.1 datasets/baselines; Tables 2/3/4; KDD DOI; official GitHub",
  },
];

if (rows.length !== 45) {
  throw new Error(`Expected 45 rows, got ${rows.length}`);
}

function csvEscape(value) {
  const text = String(value ?? "Unknown");
  return `"${text.replace(/"/g, '""')}"`;
}

for (const [index, row] of rows.entries()) {
  for (const header of headers) {
    if (!(header in row)) {
      throw new Error(`Missing field ${header} in row ${index + 1}: ${row.Paper}`);
    }
  }
}

const csv = [
  headers.map(csvEscape).join(","),
  ...rows.map((row) => headers.map((header) => csvEscape(row[header])).join(",")),
].join("\n") + "\n";

await fs.writeFile(
  new URL("../outputs/gcl_literature_table.csv", import.meta.url),
  csv,
  "utf8",
);

console.log(`Wrote ${rows.length} rows and ${headers.length} columns.`);
